# Generated by Django 5.0.7 on 2025-04-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_geographyunit_and_more'),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='available_geographies',
            field=models.ManyToManyField(blank=True, related_name='indicators', to='base.geography', verbose_name='Available Geographies'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='severity_pyramid_rungs',
            field=models.ManyToManyField(blank=True, related_name='indicators', to='base.severitypyramidrung', verbose_name='Severity Pyramid Rungs'),
        ),
    ]
