# Generated by Django 5.0.7 on 2025-05-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonDelphiIndicator',
            fields=[
            ],
            options={
                'verbose_name': 'Non-Delphi Indicator',
                'verbose_name_plural': 'Non-Delphi Indicators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('indicators.indicator',),
        ),
    ]
