# Generated by Django 5.0.7 on 2025-04-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_alter_indicator_available_geographies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='typical_revision_cadence',
            field=models.TextField(blank=True, help_text='Typical revision cadence of the indicator', verbose_name='Typical Revision Cadence'),
        ),
    ]
