# Generated by Django 5.0.7 on 2025-05-05 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_alter_indicator_geographic_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_for', to='indicators.indicator', verbose_name='Base Indicator'),
        ),
    ]
