# Generated by Django 5.0.7 on 2025-04-15 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_alter_indicator_indicator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='format_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='indicators.formattype', verbose_name='Format Type'),
        ),
    ]
