# Generated by Django 5.0.7 on 2025-04-15 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_alter_indicator_format_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='indicators.category', verbose_name='Category'),
        ),
    ]
