# Generated by Django 5.0.7 on 2025-04-17 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Display Name')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Short Name')),
                ('display_order_number', models.IntegerField(blank=True, null=True, verbose_name='Display Order Number')),
                ('used_in', models.CharField(blank=True, choices=[('indicators', 'Indicators'), ('indicatorsets', 'Indicator Sets')], help_text='Indicates where the geography is used', max_length=255, verbose_name='Used In')),
            ],
            options={
                'verbose_name': 'Geography',
                'verbose_name_plural': 'Geographies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeographyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_id', models.CharField(max_length=255, verbose_name='Geo ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Display Name')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Level')),
            ],
            options={
                'verbose_name': 'Geography Unit',
                'verbose_name_plural': 'Geography Units',
                'ordering': ['geo_id'],
            },
        ),
        migrations.CreateModel(
            name='Pathogen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Display Name')),
                ('used_in', models.CharField(blank=True, choices=[('indicators', 'Indicators'), ('indicatorsets', 'Indicator Sets')], help_text='Indicates where the pathogen is used', max_length=255, verbose_name='Used In')),
                ('display_order_number', models.IntegerField(blank=True, null=True, verbose_name='Display Order Number')),
            ],
            options={
                'verbose_name': 'Pathogen',
                'verbose_name_plural': 'Pathogens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeverityPyramidRung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Display Name')),
                ('display_order_number', models.IntegerField(blank=True, null=True, verbose_name='Display Order Number')),
                ('used_in', models.CharField(blank=True, choices=[('indicators', 'Indicators'), ('indicatorsets', 'Indicator Sets')], help_text='Indicates where the severity pyramid rung is used', max_length=255, verbose_name='Used In')),
            ],
            options={
                'verbose_name': 'Severity Pyramid Rung',
                'verbose_name_plural': 'Severity Pyramid Rungs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeographicScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('used_in', models.CharField(blank=True, choices=[('indicators', 'Indicators'), ('indicatorsets', 'Indicator Sets')], help_text='Indicates where the geographic scope is used', max_length=255, verbose_name='Used In')),
                ('display_order_number', models.IntegerField(blank=True, null=True, verbose_name='Display Order Number')),
            ],
            options={
                'verbose_name': 'Geographic Scope',
                'verbose_name_plural': 'Geographic Scopes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='geographic_scope_name_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='geographicscope',
            constraint=models.UniqueConstraint(fields=('name', 'used_in'), name='unique_geographic_scope_name_used_in'),
        ),
        migrations.AddIndex(
            model_name='geography',
            index=models.Index(fields=['name'], name='geography_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='geography',
            constraint=models.UniqueConstraint(fields=('name', 'used_in'), name='unique_geography_name_used_in'),
        ),
        migrations.AddField(
            model_name='geographyunit',
            name='geo_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geography_units', to='base.geography', verbose_name='Geography Level'),
        ),
        migrations.AddIndex(
            model_name='pathogen',
            index=models.Index(fields=['name'], name='pathogen_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='pathogen',
            constraint=models.UniqueConstraint(fields=('name', 'used_in'), name='unique_pathogen_name_used_in'),
        ),
        migrations.AddIndex(
            model_name='severitypyramidrung',
            index=models.Index(fields=['name'], name='severity_pyramid_rung_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='severitypyramidrung',
            constraint=models.UniqueConstraint(fields=('name', 'used_in'), name='unique_severity_pyramid_rung_name_used_in'),
        ),
        migrations.AddIndex(
            model_name='geographyunit',
            index=models.Index(fields=['geo_id'], name='geo_unit_geo_id_idx'),
        ),
    ]
