# Generated by Django 5.0.7 on 2025-04-15 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_id', models.CharField(max_length=255, unique=True, verbose_name='Geo ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Display Name')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Level')),
                ('geo_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geography_units', to='base.geography', verbose_name='Geography Level')),
            ],
            options={
                'verbose_name': 'Geography Unit',
                'verbose_name_plural': 'Geography Units',
                'ordering': ['geo_id'],
                'indexes': [models.Index(fields=['geo_id'], name='geo_unit_geo_id_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='geographyunit',
            constraint=models.UniqueConstraint(fields=('geo_id', 'geo_level'), name='unique_geo_unit_geo_id_geo_level'),
        ),
    ]
