# Generated by Django 5.0.7 on 2025-04-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_geographyunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathogen',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
