# Generated by Django 5.0.7 on 2025-04-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_pathogen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathogen',
            name='display_order_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Display Order Number'),
        ),
    ]
