# Generated by Django 5.0.7 on 2025-04-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_pathogen_display_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicscope',
            name='display_order_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Display Order Number'),
        ),
    ]
