# Generated by Django 5.0.7 on 2025-04-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_geographicscope_display_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Short Name'),
        ),
    ]
