# Generated by Django 5.0.7 on 2025-04-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_geography_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographyunit',
            name='geo_id',
            field=models.CharField(max_length=255, verbose_name='Geo ID'),
        ),
    ]
