# Generated by Django 5.0.7 on 2025-04-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_geographyunit_geo_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='geographyunit',
            name='unique_geo_unit_geo_id_geo_level',
        ),
    ]
