# Generated by Django 5.0.7 on 2025-04-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorsets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonDelphiIndicatorSet',
            fields=[
            ],
            options={
                'verbose_name': 'Non-Delphi Indicator Set',
                'verbose_name_plural': 'Non-Delphi Indicators Sets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('indicatorsets.indicatorset',),
        ),
    ]
