# Generated by Django 5.0.7 on 2025-04-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorsets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatorset',
            old_name='available_geographies',
            new_name='geographic_levels',
        ),
        migrations.RemoveField(
            model_name='indicatorset',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='indicatorset',
            name='geographic_granularity',
        ),
    ]
