# Generated by Django 5.0.7 on 2025-04-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorsets', '0002_rename_available_geographies_indicatorset_geographic_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorset',
            name='missingness',
            field=models.TextField(blank=True, help_text='Missingness information of the Indicator Set', verbose_name='Missingness'),
        ),
    ]
