# Generated by Django 5.0.7 on 2025-05-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorsets', '0002_nondelphiindicatorset'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorset',
            name='source_type',
            field=models.CharField(blank=True, choices=[('covidcast', 'Covidcast'), ('other_endpoint', 'Other Endpoint'), ('non_delphi', 'Non Delphi')], default='covidcast', help_text='Type of source for the indicator', max_length=255, null=True, verbose_name='Source Type'),
        ),
    ]
