# Generated by Django 5.0.7 on 2025-04-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('indicatorsets', '0003_alter_indicatorset_missingness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorset',
            name='severity_pyramid_rung',
        ),
        migrations.AddField(
            model_name='indicatorset',
            name='severity_pyramid_rungs',
            field=models.ManyToManyField(blank=True, help_text='Severity pyramid rungs of the Indicator Set', related_name='indicator_sets', to='base.severitypyramidrung', verbose_name='Severity Pyramid Rungs'),
        ),
    ]
