# Generated by Django 5.0.7 on 2025-05-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicatorsets', '0003_indicatorset_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Column Description',
                'verbose_name_plural': 'Column Descriptions',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='column_description_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='FilterDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Filter Description',
                'verbose_name_plural': 'Filter Descriptions',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='filter_description_name_idx')],
            },
        ),
    ]
