# Generated by Django 5.0.7 on 2025-04-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceSubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Display Name')),
                ('external_name', models.CharField(blank=True, max_length=255, verbose_name='External Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('license', models.CharField(blank=True, max_length=255, verbose_name='License')),
                ('dua', models.CharField(blank=True, max_length=255, verbose_name='Data Use Agreement')),
                ('datasource_name', models.CharField(blank=True, max_length=255, verbose_name='Datasource Name')),
            ],
            options={
                'verbose_name': 'Source Subdivision',
                'verbose_name_plural': 'Source Subdivisions',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='source_subdivision_name_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sourcesubdivision',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_source_subdivision_name'),
        ),
    ]
