# Generated by Django 5.0.7 on 2025-04-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcesubdivision',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sourcesubdivision',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='sourcesubdivision',
            name='external_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='External Name'),
        ),
        migrations.AlterField(
            model_name='sourcesubdivision',
            name='license',
            field=models.CharField(blank=True, max_length=255, verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='sourcesubdivision',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
